# Generated by Django 3.0.6 on 2020-05-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('vehicle_involved', models.CharField(max_length=20)),
                ('traffic_lane', models.CharField(blank=True, max_length=20, null=True)),
                ('road_type', models.CharField(blank=True, max_length=20, null=True)),
                ('junction_type', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.TimeField()),
                ('causes', models.CharField(blank=True, max_length=30, null=True)),
                ('collision_type', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_victims', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_injury', models.CharField(blank=True, max_length=10, null=True)),
                ('number_of_death', models.CharField(blank=True, max_length=10, null=True)),
                ('number_of_damage_vehicle', models.CharField(blank=True, max_length=10, null=True)),
                ('currently_allocated_to', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
