# Generated by Django 3.0.6 on 2020-05-29 01:39

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_auto_20200528_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='category_of_victims',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Driver', 'Driver'), ('Passenger', 'Passenger'), ('Trailer', 'Trailer'), ('Motorcycle', 'Motorcyclist'), ('Tricyclist', 'Tricyclist'), ('Bicyclist', 'Bicyclist'), ('Pedestrian', 'Pedestrian')], max_length=30),
        ),
        migrations.AlterField(
            model_name='incident',
            name='collision_type',
            field=models.CharField(choices=[('Mv/mv head on', 'Moving vehicles, head on'), ('Mv/mv rear end', 'Moving vehicles, rear end'), ('Mv/mv intersecting', 'Moving vehicles, intersecting'), ('Mv/mv overtake', 'Moving vehicles, overtake'), ('Mv/mv turn', 'Moving vehicles, turn'), ('Single mv hit object', 'Single moving vehicle, hit object'), ('Single mv run off', 'Single moving vehicle, run off'), ('Single mv falling off', 'Single moving vehicle, falling off'), ('Mv/pedestrian', 'Moving vehicle with pedestrian'), ('Mv/bicyclist', 'Moving vehicle with pedestrian'), ('Other', 'Other')], max_length=70),
        ),
        migrations.AlterField(
            model_name='incident',
            name='driver_precrash_factors',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Nothing notable', 'Nothing notable'), ('Fatigue/Sleepiness', 'Fatigue/Sleepiness'), ('Sudden illness', 'Sudden illness'), ('Speeding', 'Speeding'), ('Careless overtaking', 'Careless overtaking'), ('Tailgating', 'Tailgating'), ('Sudden turn', 'Sudden turn'), ('risktaking', 'Other calculated risktaking'), ('phone while driving', 'Use of phone while driving'), ('Alcohol', 'Influence of alcohol'), ('Drug', 'Influence of drug'), ('Other distractions', 'Other distractions/inattentiveness')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='road_geometry',
            field=models.CharField(choices=[('Straight road', 'Straight road'), ('Curve', 'Curve'), ('Roundabout', 'Roundabout'), ('T-junction', 'T-junction'), ('Y-junction', 'Y-junction'), ('+-junction', '+-junction'), ('Bridge', 'Bridge'), ('Road works', 'Road works'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='incident',
            name='road_type',
            field=models.CharField(choices=[('Dual carriageway', 'Dual carriageway'), ('Single carriageway', 'Single carriageway'), ('Expressway', 'Expressway'), ('Street', 'Street'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='incident',
            name='vehicle_precrash_factors',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Tyre burst', 'Tyre burst'), ('Mechanical deficiency', 'Mechanical deficiency'), ('Overloaded', 'Overloaded'), ('Defective light', 'Defective light'), ('Nothing notable', 'Nothing notable')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='vehicle_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Car saloon', 'Car saloon'), ('Microbus', 'Microbus (< 10 seater)'), ('Minibus', 'Minibus (< 15 seater)'), ('Coaster', 'Coaster (< 15 > 35 seater)'), ('Bus', 'Bus (> 35 seater)'), ('Pickup', 'Pickup'), ('SUV', 'SUV (Jeep'), ('Light lorry', 'Light lorry (< 3.5 t)'), ('Heavy lorry', 'Heavy lorry (> 3.5 t)'), ('Tanker', 'Tanker'), ('Trailer', 'Trailer'), ('Motorcycle', 'Motorcycle'), ('Tricycle', 'Tricycle'), ('Bicycle', 'Bicycle'), ('Unknown', 'Unknown')], max_length=50),
        ),
    ]
