# Generated by Django 3.0.6 on 2020-05-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0003_auto_20200529_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='if_hospital_specify',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='if_other_location_specify',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='number_of_child_victims',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='number_of_female_victims',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='number_of_male_victims',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
