# Generated by Django 3.0.6 on 2020-05-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0004_auto_20200530_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='vehicles_number_plates',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
