# Generated by Django 3.0.6 on 2020-06-01 15:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0005_incident_vehicles_number_plates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='location',
            new_name='accident_location',
        ),
        migrations.AddField(
            model_name='incident',
            name='if_other_vehicle_specify',
            field=models.CharField(blank=True, db_column='other vehicle type', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='category_of_victims',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Driver', 'Driver'), ('Passenger', 'Passenger'), ('Trailer', 'Trailer'), ('Motorcycle', 'Motorcyclist'), ('Tricyclist', 'Tricyclist'), ('Bicyclist', 'Bicyclist'), ('Pedestrian', 'Pedestrian')], help_text='If no victim, leave box unticked.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='gender_of_victims',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], help_text='If no victim, leave box unticked.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='if_hospital_specify',
            field=models.CharField(blank=True, db_column='hospital location', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='if_other_location_specify',
            field=models.CharField(blank=True, db_column='other location', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='number_of_child_victims',
            field=models.IntegerField(default=0, help_text='Number of child victims can be zero or more'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='number_of_deaths',
            field=models.IntegerField(default=0, help_text='Number of dead can be zero or more.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='number_of_female_victims',
            field=models.IntegerField(default=0, help_text='Number of female victims can be zero or more'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='number_of_injured',
            field=models.IntegerField(default=0, help_text='Number of injured can be zero or more.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='number_of_male_victims',
            field=models.IntegerField(default=0, help_text='Number of male victims can be zero or more.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='number_of_vehicles_involved',
            field=models.IntegerField(db_column='vehicles involved'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='number_of_victims',
            field=models.IntegerField(default=0, help_text='Number of victims can be zero or more.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='vehicle_precrash_factors',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Tyre burst', 'Tyre burst'), ('Mechanical deficiency', 'Mechanical deficiency'), ('Overloaded', 'Overloaded'), ('Defective light', 'Defective light'), ('Nothing notable', 'Nothing notable')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='vehicle_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Car saloon', 'Car saloon'), ('Microbus', 'Microbus (< 10 seater)'), ('Minibus', 'Minibus (< 15 seater)'), ('Coaster', 'Coaster (< 15 > 35 seater)'), ('Bus', 'Bus (> 35 seater)'), ('Pickup', 'Pickup'), ('SUV', 'SUV (Jeep'), ('Light lorry', 'Light lorry (< 3.5 t)'), ('Heavy lorry', 'Heavy lorry (> 3.5 t)'), ('Tanker', 'Tanker'), ('Trailer', 'Trailer'), ('Motorcycle', 'Motorcycle'), ('Tricycle', 'Tricycle'), ('Bicycle', 'Bicycle'), ('Unknown', 'Unknown'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='vehicles_number_plates',
            field=models.CharField(blank=True, help_text='You can add more than one vehicle number plate.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='victims_age_group',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Baby', 'Baby'), ('Toddler', 'Toddler'), ('Child', 'Child'), ('Teenager', 'Teenager'), ('Adult', 'Adult'), ('Middle aged', 'Middle aged'), ('Elderly', 'Elderly')], help_text='If no victim, leave box unticked.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='victims_current_location',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Accident Scene'), (2, 'Hospital'), (3, 'Other')], help_text='If no victim, leave box unticked.', max_length=50, null=True),
        ),
    ]
