# Generated by Django 3.0.6 on 2020-06-01 20:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0006_auto_20200601_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='gender_of_victims',
        ),
        migrations.AddField(
            model_name='incident',
            name='nearest_landmark',
            field=models.CharField(blank=True, help_text='By landmark we mean somewhere notable such as bustop, market, hotel, hospital etc.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='category_of_victims',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Driver', 'Driver'), ('Passenger', 'Passenger'), ('Motorcycle', 'Motorcyclist'), ('Tricyclist', 'Tricyclist'), ('Bicyclist', 'Bicyclist'), ('Pedestrian', 'Pedestrian')], help_text='If no victim, leave boxes unticked.', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='number_of_damaged_vehicles',
            field=models.IntegerField(default=0, help_text='Number of damaged vehicles can be zero or more.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='victims_age_group',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Baby', 'Baby'), ('Toddler', 'Toddler'), ('Child', 'Child'), ('Teenager', 'Teenager'), ('Adult', 'Adult'), ('Middle aged', 'Middle aged'), ('Elderly', 'Elderly')], help_text='If no victim, leave boxes unticked.', max_length=50, null=True),
        ),
    ]
