# Generated by Django 3.0.6 on 2020-06-07 15:14

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0010_remove_incident_number_of_damaged_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='local_government_area',
            field=models.CharField(db_column='LGA', default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='driver_precrash_factors',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Nothing notable', 'Nothing notable'), ('Fatigue/Sleepiness', 'Fatigue/Sleepiness'), ('Sudden illness', 'Sudden illness'), ('Speeding', 'Speeding'), ('Careless overtaking', 'Careless overtaking'), ('Tailgating', 'Tailgating'), ('Sudden turn', 'Sudden turn'), ('risktaking', 'Other calculated risktaking'), ('phone while driving', 'Use of phone while driving'), ('Alcohol', 'Influence of alcohol'), ('Drug', 'Influence of drug'), ('Other distractions', 'Other distractions/inattentiveness')], help_text='This field is required', max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='number_of_child_victims',
            field=models.PositiveIntegerField(help_text='Number of child victims can be zero or more'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='number_of_deaths',
            field=models.PositiveIntegerField(help_text='Number of dead can be zero or more.'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='number_of_female_victims',
            field=models.PositiveIntegerField(help_text='Number of female victims can be zero or more'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='number_of_injured',
            field=models.PositiveIntegerField(help_text='Number of injured can be zero or more.'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='number_of_male_victims',
            field=models.PositiveIntegerField(help_text='Number of male victims can be zero or more.'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='number_of_vehicles_involved',
            field=models.PositiveIntegerField(db_column='vehicles involved', help_text='Number of vehicles can be zero or more.'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='number_of_victims',
            field=models.PositiveIntegerField(help_text='Number of victims can be zero or more.'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='vehicles_precrash_factors',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Tyre burst', 'Tyre burst'), ('Mechanical deficiency', 'Mechanical deficiency'), ('Overloaded', 'Overloaded'), ('Defective light', 'Defective light'), ('Nothing notable', 'Nothing notable')], help_text='This field is required', max_length=50),
        ),
    ]
