# Generated by Django 3.0.6 on 2020-06-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0011_auto_20200607_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='videofile',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='upload a video or an image'),
        ),
        migrations.AddField(
            model_name='incident',
            name='your_category',
            field=models.CharField(choices=[('Victim', 'Accident victim'), ('Eye nitness', 'Eye witness'), ('Driver', 'Driver of a vehicle in the accident')], db_column='User category', default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='collision_type',
            field=models.CharField(choices=[('Mv/mv head on', 'Moving vehicles, head on'), ('Mv/mv rear end', 'Moving vehicles, rear end'), ('Mv/mv intersecting', 'Moving vehicles, intersecting'), ('Mv/mv overtake', 'Moving vehicles, overtake'), ('Mv/mv turn', 'Moving vehicles, turn'), ('Single mv hit object', 'Single moving vehicle, hit object'), ('Single mv run off', 'Single moving vehicle, run off'), ('Single mv falling off', 'Single moving vehicle, falling off'), ('Mv/pedestrian', 'Moving vehicle with pedestrian'), ('Mv/motorcyclist', 'Moving vehicle with motorcyclist'), ('Mv/bicyclist', 'Moving vehicle with bicyclist'), ('Other', 'Other')], max_length=70),
        ),
    ]
