# Generated by Django 3.0.7 on 2020-06-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_Of_Accident', models.CharField(choices=[('Riot Prone Area', 'Prone Area'), ('Cultist Area', 'Cultist Area'), ('Kidnapping', 'Kidnaping'), ('Arm Robbers station', 'Arm Robbers station'), ('Gang of Area Boys', 'Gang of Area Boys'), ('Bandits', 'Bandits'), ('Hilly area', 'Hilly area')], default='', max_length=100)),
                ('full_Name', models.CharField(blank=True, default='', max_length=20)),
                ('Along_the_Way', models.CharField(blank=True, default='', max_length=20)),
                ('Description_Of_the_Area', models.TextField(blank=True, default='')),
                ('Photo_of_Area', models.ImageField(default='scan', upload_to='images/')),
            ],
        ),
    ]
