# Generated by Django 3.0.7 on 2020-06-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NonCollisionApp', '0003_auto_20200606_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsedetails',
            name='Incident_happening',
            field=models.CharField(choices=[('Select', 'Select'), ('Cultist Activities', 'Cultist Activities'), ('Kidnappers', 'Kidnapppers'), ('Arm Robbers station', 'Arm Robbers station'), ('Gang of Area Boys', 'Gang of Area Boys'), ('Bandits', 'Bandits'), ('Hilly area', 'Hilly area')], default='Select', max_length=100),
        ),
    ]
