# Generated by Django 3.0.7 on 2020-06-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NonCollisionApp', '0004_auto_20200606_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('capital', models.CharField(blank=True, max_length=45, null=True)),
                ('zone', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.AlterField(
            model_name='responsedetails',
            name='Along_the_Way',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='responsedetails',
            name='LG_Area',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
