# Generated by Django 3.0.7 on 2020-06-08 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NonCollisionApp', '0005_auto_20200608_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgas', to='NonCollisionApp.State')),
            ],
            options={
                'verbose_name': 'LGA',
                'verbose_name_plural': 'LGAs',
            },
        ),
    ]
