# Generated by Django 3.0.7 on 2020-06-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NonCollisionApp', '0006_lga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsedetails',
            name='Incident_happening',
            field=models.CharField(choices=[('Cultist Activities', 'Cultist Activities'), ('Kidnappers', 'Kidnapppers'), ('Arm Robbers station', 'Arm Robbers station'), ('Gang of Area Boys', 'Gang of Area Boys'), ('Bandits', 'Bandits'), ('Hilly area', 'Hilly area'), ('Others', 'Others')], default='Cultist Activities', max_length=100),
        ),
        migrations.AlterField(
            model_name='responsedetails',
            name='State',
            field=models.CharField(default='', max_length=20),
        ),
    ]
