# Generated by Django 3.0.6 on 2020-06-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0013_auto_20200609_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='if_other_category_specify',
            field=models.CharField(blank=True, db_column='User other category', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='your_category',
            field=models.CharField(choices=[('Victim', 'Accident victim'), ('Eye nitness', 'Eye witness'), ('Driver', 'Driver of a vehicle in the accident'), ('Other', 'Other')], db_column='User category', max_length=30),
        ),
    ]
