# Generated by Django 3.0.6 on 2020-06-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0008_auto_20200608_1958'),
        ('usersapp', '0014_auto_20200609_0454'),
    ]

    operations = [
    ]
