# Generated by Django 3.0.6 on 2020-05-11 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LG_ID',
            fields=[
                ('local_govt_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='STATE_ID',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=45)),
                ('state_capital', models.CharField(max_length=45)),
                ('state_zone', models.CharField(max_length=45)),
                ('local_govt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zoitapp.LG_ID')),
            ],
        ),
        migrations.CreateModel(
            name='Police_Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_station_division', models.CharField(max_length=45)),
                ('police_station_address', models.CharField(max_length=100)),
                ('police_station_email', models.CharField(max_length=50, unique=True)),
                ('police_station_phone', models.CharField(max_length=45)),
                ('local_govt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zoitapp.LG_ID')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zoitapp.STATE_ID')),
            ],
        ),
        migrations.CreateModel(
            name='Local_Government',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_govt_name', models.CharField(max_length=45)),
                ('local_govt_hqrt', models.CharField(max_length=45)),
                ('local_govt_zone', models.CharField(max_length=45)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zoitapp.STATE_ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=45)),
                ('hotel_phone', models.CharField(max_length=45)),
                ('hotel_email', models.CharField(max_length=50, unique=True)),
                ('hotel_address', models.CharField(max_length=100)),
                ('local_govt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zoitapp.LG_ID')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zoitapp.STATE_ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=45)),
                ('hospital_type', models.CharField(max_length=45)),
                ('hospital_phone', models.CharField(max_length=45)),
                ('hospital_email', models.CharField(max_length=50, unique=True)),
                ('hospital_address', models.CharField(max_length=100)),
                ('local_govt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zoitapp.LG_ID')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zoitapp.STATE_ID')),
            ],
        ),
        migrations.CreateModel(
            name='FRSC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frsc_address', models.CharField(max_length=100)),
                ('frsc_email', models.CharField(max_length=50, unique=True)),
                ('frsc_phone', models.CharField(max_length=45)),
                ('local_govt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zoitapp.LG_ID')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zoitapp.STATE_ID')),
            ],
        ),
    ]
