# Generated by Django 3.0.6 on 2020-05-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoitapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frsc',
            old_name='state_id',
            new_name='State',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='state_id',
            new_name='State',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='state_id',
            new_name='State',
        ),
        migrations.RenameField(
            model_name='local_government',
            old_name='state_id',
            new_name='State',
        ),
        migrations.RenameField(
            model_name='police_station',
            old_name='state_id',
            new_name='State',
        ),
        migrations.RemoveField(
            model_name='state',
            name='local_govt_id',
        ),
        migrations.AlterField(
            model_name='frsc',
            name='frsc_email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='police_station',
            name='police_station_email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
