# Generated by Django 3.0.6 on 2020-06-04 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zoitapp', '0003_auto_20200604_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('zone', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'LGA',
                'verbose_name_plural': 'LGAs',
            },
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=45, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('lga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='Zoitapp.LGA')),
            ],
            options={
                'verbose_name': 'PoliceStation',
                'verbose_name_plural': 'PoliceStations',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='local_government',
            name='State',
        ),
        migrations.RemoveField(
            model_name='police_station',
            name='State',
        ),
        migrations.RemoveField(
            model_name='police_station',
            name='local_govt_id',
        ),
        migrations.AlterModelOptions(
            name='frsc',
            options={'managed': True, 'verbose_name': 'FRSC', 'verbose_name_plural': 'FRSC'},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'managed': True, 'verbose_name': 'Hospital', 'verbose_name_plural': 'Hospitals'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'managed': True, 'verbose_name': 'Hotel', 'verbose_name_plural': 'Hotels'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
        migrations.RenameField(
            model_name='frsc',
            old_name='frsc_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='frsc',
            old_name='frsc_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='hospital_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='hospital_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='hospital_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state_capital',
            new_name='capital',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state_zone',
            new_name='zone',
        ),
        migrations.RemoveField(
            model_name='frsc',
            name='State',
        ),
        migrations.RemoveField(
            model_name='frsc',
            name='frsc_email',
        ),
        migrations.RemoveField(
            model_name='frsc',
            name='local_govt_id',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='State',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='hospital_email',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='local_govt_id',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='State',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_email',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='local_govt_id',
        ),
        migrations.AddField(
            model_name='frsc',
            name='command',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='frsc',
            name='email',
            field=models.EmailField(blank=True, max_length=45, unique=True),
        ),
        migrations.AddField(
            model_name='frsc',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='road_safety', to='Zoitapp.State'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='email',
            field=models.EmailField(blank=True, max_length=45, unique=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='mortuary',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='Zoitapp.State'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.EmailField(blank=True, max_length=45, unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospitality', to='Zoitapp.State'),
        ),
        migrations.DeleteModel(
            name='LG_ID',
        ),
        migrations.DeleteModel(
            name='Local_Government',
        ),
        migrations.DeleteModel(
            name='Police_Station',
        ),
        migrations.DeleteModel(
            name='STATE_ID',
        ),
        migrations.AddField(
            model_name='policestation',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='Zoitapp.State'),
        ),
        migrations.AddField(
            model_name='lga',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgas', to='Zoitapp.State'),
        ),
        migrations.AddField(
            model_name='frsc',
            name='lga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='road_safety', to='Zoitapp.LGA'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='lga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='Zoitapp.LGA'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='lga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospitality', to='Zoitapp.LGA'),
        ),
    ]
