# Generated by Django 3.0.6 on 2020-06-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zoitapp', '0004_auto_20200604_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lga',
            old_name='State',
            new_name='state',
        ),
    ]
