# Generated by Django 3.0.6 on 2020-06-07 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zoitapp', '0005_auto_20200605_1804'),
    ]

    operations = [
    ]
