# Generated by Django 3.0.6 on 2020-06-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zoitapp', '0006_auto_20200607_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lga',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='policestation',
            name='email',
        ),
    ]
